import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-white shadow p-6 flex justify-between items-center">
          <h1 className="text-2xl font-bold text-[#7200a2]"><Link href="/">George Anthony</Link></h1>
          <nav className="space-x-6">
            <a href="quote" className="hover:text-[#7200a2]">Get a Quote</a>
            <a href="#about" className="hover:text-[#7200a2]">About</a>
            <a href="#contact" className="hover:text-[#7200a2]">Contact</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
